# Generated by Django 5.0 on 2023-12-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movieifo',
            new_name='Movieinfo',
        ),
    ]
