# Generated by Django 5.0 on 2023-12-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movieifo_movieinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
